services:

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    pull_policy: never
    restart: always
    env_file:
      - .env
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress
    pull_policy: never
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: nginx
    pull_policy: never
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception

networks:
  inception:
    driver: bridge
