services:

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    pull_policy: never
    restart: always
    env_file:
      - .env
    networks:
      - inception

networks:
  inception:
    driver: bridge
